In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("stock_data.csv")
df.head()

,Unnamed: 0,open,open.1,open.2,open.3,open.4,open.5,open.6,open.7,open.8,...,volume.14,volume.15,volume.16,volume.17,volume.18,volume.19,volume.20,volume.21,volume.22,volume.23
0,symbol,AAPL,ABBV,AMZN,AVGO,BAC,BRK-B,COST,CVX,GOOG,...,META,MSFT,MU,NFLX,NVDA,ORCL,TSLA,V,WMT,XOM
1,date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-02,27.84749984741211,65.44000244140625,15.628999710083008,10.093000411987305,17.989999771118164,151.5,141.8699951171875,111.62999725341797,26.37807846069336,...,18177500.0,27913900.0,15138200.0,134750000.0,113680000.0,15070200.0,71466000.0,8389600.0,13505400.0,10220400.0
3,2015-01-05,27.072500228881836,65.5,15.350500106811523,10.006999969482422,17.790000915527344,148.80999755859375,141.69000244140625,110.95999908447266,26.091365814208984,...,26452200.0,39673900.0,23706600.0,181650000.0,197952000.0,18369400.0,80527500.0,12751200.0,20937000.0,18502400.0
4,2015-01-06,26.635000228881836,65.62000274658203,15.112000465393066,9.895000457763672,17.420000076293945,147.63999938964844,140.61000061035156,107.87000274658203,25.67949676513672,...,27399300.0,36447900.0,40092000.0,160377000.0,197764000.0,19229500.0,93928500.0,11070000.0,24615300.0,16670700.0

In [3]:
import pandas as pd

raw = pd.read_csv("stock_data.csv")
symbols = raw.iloc[0]
df = raw.iloc[2:].copy()

df = df.rename(columns={"Unnamed: 0": "date"})
df["date"] = pd.to_datetime(df["date"])
data_cols = df.columns[1:]

new_cols = []
for col in data_cols:
    field = col.split(".")[0]      # open/high/low/adjclose/volume
    company = symbols[col]         # AAPL, XOM, ...
    new_cols.append((company, field))

df_data = df[data_cols].copy()
df_data.columns = pd.MultiIndex.from_tuples(new_cols, names=["company", "field"])


df_data.index = df["date"]

result = df_data.stack(level="company")
result.index = result.index.set_names(["date", "company"])
result = result.swaplevel().sort_index()

print(result.head())

field                             open                high  \
company date
AAPL    2015-01-02   27.84749984741211  27.860000610351562
        2015-01-05  27.072500228881836  27.162500381469727
        2015-01-06  26.635000228881836  26.857500076293945
        2015-01-07  26.799999237060547  27.049999237060547
        2015-01-08    27.3075008392334  28.037500381469727

field                              low            adjclose       volume
company date
AAPL    2015-01-02  26.837499618530273  24.214895248413086  212818400.0
        2015-01-05  26.352500915527344  23.532724380493164  257142000.0
        2015-01-06  26.157499313354492  23.534931182861328  263188400.0
        2015-01-07  26.674999237060547   23.86494255065918  160423600.0
        2015-01-08  27.174999237060547   24.78189468383789  237458000.0

/tmp/ipykernel_2327/2214247361.py:23: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  result = df_data.stack(level="company")

In [4]:
result

field                             open                high  \
company date
AAPL    2015-01-02   27.84749984741211  27.860000610351562
        2015-01-05  27.072500228881836  27.162500381469727
        2015-01-06  26.635000228881836  26.857500076293945
        2015-01-07  26.799999237060547  27.049999237060547
        2015-01-08    27.3075008392334  28.037500381469727
...                                ...                 ...
XOM     2025-12-23  118.47000122070312  120.02999877929688
        2025-12-24  119.33000183105469  120.05000305175781
        2025-12-26  118.88999938964844  119.55000305175781
        2025-12-29   120.1500015258789  121.30000305175781
        2025-12-30   121.0999984741211  121.80000305175781

field                              low            adjclose       volume
company date
AAPL    2015-01-02  26.837499618530273  24.214895248413086  212818400.0
        2015-01-05  26.352500915527344  23.532724380493164  257142000.0
        2015-01-06  26.157499313354492  23.534931182861328  263188400.0
        2015-01-07  26.674999237060547   23.86494255065918  160423600.0
        2015-01-08  27.174999237060547   24.78189468383789  237458000.0
...                                ...                 ...          ...
XOM     2025-12-23  118.31999969482422  118.62928771972656   12567600.0
        2025-12-24  119.12000274658203  118.43061828613281    6137400.0
        2025-12-26  118.52999877929688  118.32134246826172    8066100.0
        2025-12-29   119.4000015258789  119.73194122314453   14782500.0
        2025-12-30  120.62999725341797  120.18889617919922   11150500.0

[66360 rows x 5 columns]

In [5]:

df = result.copy()

df = df.sort_index()

In [6]:
import pandas as pd
import numpy as np

df = df.sort_values(['company', 'date']).copy()
g = df.groupby('company')

In [7]:
num_cols = ["open", "high", "low", "adjclose", "volume"]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [8]:
# signal 1: 5 days reverse
df['signal1'] = -g['adjclose'].pct_change(5)

In [9]:
# signal 2: ma20 - ma5
ret_20 = g['adjclose'].pct_change(20)
ret_5 = g['adjclose'].pct_change(5)

df['signal2'] = ret_20 - ret_5

In [10]:
# signal 3: ma60 - ma10
ret_10 = g['adjclose'].pct_change(10)
ret_60 = g['adjclose'].pct_change(60)

df['signal3'] = ret_10 - ret_60

In [11]:
# signal 4: 20 days return / 20 days volatility
df['ret_1d'] = g['adjclose'].pct_change()
vol_20 = (
    df.groupby('company')['ret_1d']
      .rolling(20, min_periods=20)
      .std()
      .reset_index(level=0, drop=True)
)

ret_20 = g['adjclose'].pct_change(20)

df['signal4'] = ret_20 / (vol_20 * np.sqrt(20))

In [12]:
# signal 5:gap_revert

prev_close = g['adjclose'].shift(1)
df['signal5'] = -((df['open'] - prev_close) / prev_close)

In [13]:
# signal 6: volume suprise
vol_ma_20 = (
    g['volume']
    .rolling(20, min_periods=20)
    .mean()
    .reset_index(level=0, drop=True)
)
df['signal6'] = np.log(df['volume'] / vol_ma_20)

In [14]:
# signal 7: tr/atr
prev_close = g['adjclose'].shift(1)

tr = np.maximum(
    df['high'] - df['low'],
    np.maximum(
        (df['high'] - prev_close).abs(),
        (df['low'] - prev_close).abs()
    )
)

atr_20 = (
    tr.groupby('company')
    .rolling(20, min_periods=20)
    .mean()
    .reset_index(level=0, drop=True)
)

df['signal7'] = tr / atr_20

In [15]:
# signal 8: illiquidity
df['ret_1d'] = g['adjclose'].pct_change()
df['dollar_vol'] = df['adjclose'] * df['volume']
illiq_daily = df['ret_1d'].abs() / df['dollar_vol'].replace(0, np.nan)
df['signal8'] = (
    illiq_daily.groupby('company')
    .rolling(20, min_periods=20)
    .mean()
    .reset_index(level=0, drop=True)
)

In [16]:
df.columns

Index(['open', 'high', 'low', 'adjclose', 'volume', 'signal1', 'signal2',
       'signal3', 'ret_1d', 'signal4', 'signal5', 'signal6', 'signal7',
       'dollar_vol', 'signal8'],
      dtype='object', name='field')

In [17]:
daily_signal = df[[ 'signal1', 'signal2',
       'signal3',  'signal4', 'signal5', 'signal6', 'signal7',
        'signal8']]

In [21]:
daily_signal.to_csv('daily_signal.csv')